### PR TITLE
Initial C implementation

### PR DESCRIPTION
**Pull request by reagent**

### CODE REVIEW

**Comment by dce** [comment]
Got an error running one of the specs:

```
Building all languages ...
  * Entering directory 'languages/C'
    * Running task 'C:clean'... done.
    * Running task 'C:build'... done.
    * Running tests...failed.
Run options: --seed 59608

# Running:

.F....

Finished in 0.031863s, 188.3062 runs/s, 188.3062 assertions/s.

  1) Failure:
OtpTest#test_encrypt_then_decrypt [./test/otp_test.rb:55]:
--- expected
+++ actual
@@ -1 +1 @@
-"this is the secret message"
+"this is the secr?\x91\xAC_?}p4\x8FE"


6 runs, 6 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by reagent** [comment]
I was getting that before too, but then it went away.  I'm still seeing it sporadically but can't reliably reproduce it.  I'm going to switch back to an alternate implementation.

**Comment by dce** [comment]
Ah, yeah you're right. Can't reproduce.

**Comment by dce** [comment]
Or rather, not predictably.

**Comment by reagent** [comment]
Pull latest and try again -- I was using `snprintf` but reverted to doing it by hand.

**Comment by dce** [comment]
Same issue, though very intermittently.

**Comment by reagent** [comment]
Ok, I put a test harness around this and was able to reproduce and debug the issue.  I wasn't properly terminating strings and incrementing an iterator when reading from STDIN.  The result was that for input > my buffer size (32), I was seeing intermittent corruption.  Strange that it wasn't happening every time.

Here's the test code -- ran it for 93k iterations with no problems before I exited: 

```ruby
start_message = "this is the secret message"
counter       = 0

while(1) do
  end_message = `/bin/bash -c 'echo -n "#{start_message}"' | ./encrypt deadbeef 2> encrypt.stderr | ./decrypt deadbeef 2> decrypt.stderr`.chomp

  if end_message != start_message
    puts "comparison failed on #{counter} pass: '#{end_message}' != '#{start_message}'"
    puts "Encrypt STDERR output:"
    system('cat encrypt.stderr')
    puts "Decrypt STDERR output:"
    system('cat decrypt.stderr')
    break;
  end

  puts "Pass #{counter}" if (counter % 100 == 0)

  counter += 1
end
```

**Comment by dce** [comment]
:+1: :100:

**Comment by dce** [comment]
I'd say this is good to merge.

**Pull request merged**
