### PR TITLE
Dis Go

### PR DESCRIPTION
**Pull request by Fosome**

### CODE REVIEW

**Comment by dce** [comment]
Gettin dis when I run `rake`:

```
  * Entering directory 'languages/Go'
    * Running task 'Go:clean'... done.
    * Running task 'Go:build'... encrypt.go:8:2: cannot find package "otp/languages/Go/key" in any of:
	/usr/local/Cellar/go/1.2/libexec/src/pkg/otp/languages/Go/key (from $GOROOT)
	/Users/dce/gocode/src/otp/languages/Go/key (from $GOPATH)
decrypt.go:8:2: cannot find package "otp/languages/Go/key" in any of:
	/usr/local/Cellar/go/1.2/libexec/src/pkg/otp/languages/Go/key (from $GOROOT)
	/Users/dce/gocode/src/otp/languages/Go/key (from $GOPATH)
done.
    * Running tests...sh: ./languages/Go/encrypt: No such file or directory
sh: ./languages/Go/decrypt: No such file or directory
sh: ./languages/Go/encrypt: No such file or directory
sh: ./languages/Go/decrypt: No such file or directory
failed.
Run options: --seed 63931

# Running:

EEEEF.

Finished in 0.012815s, 468.2013 runs/s, 156.0671 assertions/s.

  1) Error:
OtpTest#test_decrypt_with_zero_key:
Errno::ENOENT: No such file or directory - ./languages/Go/decrypt
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:193:in `spawn'
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:193:in `popen_run'
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:145:in `popen2'
    ./test/otp_test.rb:9:in `run_program'
    ./test/otp_test.rb:32:in `test_decrypt_with_zero_key'


  2) Error:
OtpTest#test_encrypt_multiple_chars_with_zero_key:
Errno::ENOENT: No such file or directory - ./languages/Go/encrypt
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:193:in `spawn'
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:193:in `popen_run'
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:145:in `popen2'
    ./test/otp_test.rb:9:in `run_program'
    ./test/otp_test.rb:23:in `test_encrypt_multiple_chars_with_zero_key'


  3) Error:
OtpTest#test_encrypt_with_long_message_and_key:
Errno::ENOENT: No such file or directory - ./languages/Go/encrypt
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:193:in `spawn'
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:193:in `popen_run'
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:145:in `popen2'
    ./test/otp_test.rb:9:in `run_program'
    ./test/otp_test.rb:41:in `test_encrypt_with_long_message_and_key'


  4) Error:
OtpTest#test_encrypt_single_char_with_zero_key:
Errno::ENOENT: No such file or directory - ./languages/Go/encrypt
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:193:in `spawn'
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:193:in `popen_run'
    /Users/dce/.rbenv/versions/2.1.4/lib/ruby/2.1.0/open3.rb:145:in `popen2'
    ./test/otp_test.rb:9:in `run_program'
    ./test/otp_test.rb:13:in `test_encrypt_single_char_with_zero_key'


  5) Failure:
OtpTest#test_encrypt_then_decrypt [./test/otp_test.rb:55]:
Expected: "this is the secret message"
  Actual: ""

6 runs, 2 assertions, 1 failures, 4 errors, 0 skips
```

Do I need to change my `$GOPATH` somehow?

**Comment by Fosome** [comment]
@dce kk doge, check em now

**Comment by dce** [comment]
:+1: worked.

**Comment by dce** [comment]
:b: :zzz:

**Pull request closed without merging**
