### PR TITLE
Ada 2012 version

### PR DESCRIPTION
**Pull request by HadrienG2**
Howdy !

While browsing around the web, I ended up on your OTP challenge, and couldn't resist the temptation to try making a version in my favorite language, Ada 2012.

My proposal was tested with GNAT GPL 2015 from Adacore ( http://libre.adacore.com/ ), but should also work with the versions of GNAT that are distributed as part of linux distros (package "gnat" in Debian derivatives), provided that you also install GPRbuild (package "gprbuild" in Debian derivatives).

Please do not hesitate to try it out and tell me what you think ! In particular, I do not have an install of rake handy, so I had to do a bit of guesswork when writing my rakefile and could not test it. However, I checked that the program passes the test suite manually.

### CODE REVIEW

**Comment by dce** [comment]
Hey @Neolander! This is super cool. I've made a couple changes locally to get the tests passing, and I'm hitting a snag. Your `encrypt` and `decrypt` programs always output a newline character, which is not what the test suite is expecting. Do you have any idea how to change this behavior?

**Comment by Neolander** [comment]
Hmmm, that's really strange. I am not outputting newlines myself, so my guess would be that it is the GNAT runtime itself that tries to be helpful to bad programmers, and does something which is counterproductive in our case.

I'm going to ask the GNAT team about that. In the meantime, an ugly workaround would be to wrap calls in an echo -n, like so :

 echo -n `echo -n 'a' | ./obj/encrypt.exe 0`

But that is obviously very unsatisfactory.

**Comment by dce** [comment]
Relevant: http://objectmix.com/ada/317300-newline-simple-program.html

**Comment by Neolander** [comment]
Well, I find it strange that I have to use a compiler-specific workaround in order to address this, but... I implemented the suggestion of that page in the latest commit.

**Comment by Neolander** [comment]
After chatting with Adacore employees, it seems that this newline behavior is intended by the Ada standard Text_IO package, but there are other ways to output text in the Ada standard library that do not have this restriction. I will investigate this more tomorrow, as it is getting late here.

**Comment by dce** [comment]
Made a couple small changes to get the test suite passing: https://github.com/Neolander/otp/pull/1. Fun stuff -- never played w/ Ada before.

**Comment by Neolander** [comment]
The latest commit should not output trailing newlines, and it uses only standard Ada packages. Does it work on your side?

**Comment by dce** [comment]
Indeed it does. Should I go ahead and merge?

**Comment by Neolander** [comment]
Just tried out stricter GNAT warnings as a last check before merging, which revealed many missed opportunities for making variable consts. Now I think everything is ready for merging.

**Comment by dce** [comment]
Done. Awesome. Thanks!

**Comment by dce** [comment]
Post updated: https://viget.com/extend/otp-a-language-agnostic-programming-challenge

**Comment by HadrienG2** [comment]
My pleasure ;)

**Pull request merged**
